gText_Birch_Welcome::
    .string "Hello! It's so nice to finally\n"
	.string "meet you.\p"
	.string "My name is Aspen. I'm the Pokémon\n"
	.string "Professor here in the Admiro region.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I research all of the many\n"
	.string "different kinds of Pokémon that are\l"
	.string "found here.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I recently reached out to my\n"
	.string "colleague, Oak, to ask if he knew\l"
	.string "anyone who would be interested in\l"
	.string "helping us with our research.\p"
	.string "He told me that you were one of\n"
	.string "the best trainers in Kanto,\l"
	.string "and that you were looking to move\l"
	.string "to a new region.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, forgive my spotty memory.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "Now remind me, what was your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Okay, I've got it.\p"
	.string "You're {PLAYER}{KUN} who will be\n"
	.string "moving to my hometown of Periwinkle.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "It's quite a long way from Kanto.\p"
	.string "I wish you safe travels,\n"
	.string "and I look forward to working with you!\p"
	.string "Come meet me in my lab once you\n"
	.string "unpack and get settled into your\l"
	.string "new home.\p"
	.string "$"
